name: Versatile PyInstaller
uses: sayyid5416/pyinstaller@v1.8.0
on:
    push:
    pull_request:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                - info
                - warning
                - debug
jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python-version: 3.14
          pyinstaller_ver: '==6.14.0'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'steamPathCLI'
          options: --onefile, --name "SteamPathsCLI",
          spec_options: # any custom arguments you want like: `--debug`