name: Package Application with PyInstaller
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"

      - name: Install dependencies
        run: >
          python -m pip install --upgrade pip

          pip install .  # Install dependencies; modify if using requirements.txt

      - name: Package Application with PyInstaller
        run: |
          pyinstaller steamPathCLI.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: steamPathCLI.sh
          path: dist/steamPathCLI.sh
